name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <=3.0.5"

dependencies:
  animated_text_kit: ^4.2.2
  cloud_firestore: ^4.8.3
  cupertino_icons: ^1.0.5
  firebase_auth: ^4.7.1
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter

  # cupertino_icons: ^0.1.2
  # animated_text_kit: ^1.3.0
  # firebase_core: ^0.8.0-nullsafety.1
  # firebase_auth: ^1.0.0-1.0.nullsafety.0
  # cloud_firestore: ^0.17.0-1.0.nullsafety.2
  modal_progress_hud_nsn: ^0.1.0-nullsafety-0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
